# Generated by Django 4.0.6 on 2022-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_reaction_unique_together_reaction_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
